### ISSUE TITLE
Missing helpers-1.3.5.jar in 1.3.5 Release

### ISSUE THREAD

**Issue by AlexanderLS** [danielgindi/android-helpers#2]
**Problem:** 
Missing `helpers-1.3.5.jar` in 1.3.5 Release
**Why:** 
Gradle bug
**Solution:** 
Update in the main build.gradle  `classpath 'com.android.tools.build:gradle:3.1.3'` to `classpath 'com.android.tools.build:gradle:3.3.0-alpha03'`
Update in the gradle-wrapper.properties `distributionUrl=https\://services.gradle.org/distributions/gradle-4.5-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-rc-1-all.zip'
**Solution test:** 
PASS

**Comment by danielgindi** [comment]
Thank you!
I'm re-publishing now with the fix
